export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh
export SHELL_SESSION_HISTORY=0

zplug 'mafredri/zsh-async'
zplug 'sindresorhus/pure'
zplug 'zsh-users/zsh-syntax-highlighting'
zplug 'zsh-users/zsh-completions'
zplug load

# autoload -U promptinit; promptinit
# prompt pure
export EDITOR='vim'

COMPLETION_WAITING_DOTS="true"

stty -ixon -ixoff 
stty start undef stop undef

alias ls='ls -FG'
alias ez="vim  ~/.zshrc"
alias sz="source  ~/.zshrc"
alias et="vim ~/.tmux.conf"
alias be="bundle exec"
alias delbranch='git branch -D'
alias branches="git branch --sort=committerdate"
alias compose="sudo docker-compose up -d"
alias tx="tmuxinator"

alias tadb="heroku pg:psql -a truva-acceptance"
alias tarc="heroku run bundle exec rails console -a truva-acceptance"
alias aok="rubocop && yarn lint && yarn test && rspec"

export NVM_DIR="/Users/eric.firth/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.

# No arguments: `git status`
# # With arguments: acts like `git`
g() {
  if [[ $# > 0 ]]; then
    git $@
  else
    git status
  fi
}

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
# Complete g like git
compdef g=git

export PATH="$HOME/.rbenv/bin:$PATH:$HOME/.rbenv/shims"
eval "$(rbenv init -)"
